### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by subtirelumihail** [remobile/react-native-splashscreen#18]
I followed your instructions and I can't manage to get this working ...

**Comment by dunhuang** [comment]
in left panel, select RCTSplashScreen.xcodeproj, then select 'TARGETS-> RCTSplashScreen' in the right. Activate the 'Build Setting' tab,  in the 'Headers search Paths' line, add '$(SRCROOT)/../../react-native/React', 'recursive'

**Comment by mehcode** [comment]
This was fixed in the https://github.com/mehcode/rn-splash-screen fork

**Comment by walkerrandolphsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/1386741/18805656/ab7f3b6c-81e1-11e6-8da5-017ab35ee87d.png)

@dunhuang I believe I have done what you mentioned, however I still get a build failure like the issue describes. Any ideas?

**Comment by dunhuang** [comment]
@walkerrandolphsmith i think you should pay attention to the path, yours is different with mine

**Comment by walkerrandolphsmith** [comment]
@dunhuang thanks, yes `$(SRCROOT)/../../react-native/React` and `$(SRCROOT)/../react-native/React` are different and that was my problem.

**Comment by TylerYang** [comment]
+1
